name: localduareapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts:
  http:
  shimmer:
  flutter: 
    sdk: flutter
  pin_input_text_field: ^4.5.2
  text_form_field_validator: ^0.0.3
  shared_preferences:
  cached_network_image: ^3.2.3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/

